version: '3.8'

services:
  # 1. Dịch vụ Cơ sở dữ liệu MySQL
  db:
    image: mysql:8.0
    container_name: b6_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_campus_db
      MYSQL_USER: campus_user
      MYSQL_PASSWORD: campus_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 2. Giao diện Web quản lý Database (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: b6_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

# Khai báo volume để dữ liệu không bị mất khi tắt Docker
volumes:
  mysql_data: